version: "3.8"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5986:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - D:/yianzhuang/dist:/usr/local/lib/node_modules/n8n/node_modules/n8n-editor-ui/dist
    environment:
      - NODE_ENV=production
      - N8N_DEFAULT_LOCALE=zh-CN
      - GENERIC_TIMEZONE=Asia/Shanghai
volumes:
  n8n_data:
    external: false 